# Exploring the Bitcoin Blockchain Data

<p>Let us examine the latest block of the bitcoin blockchain and understand what sort of accounts are invloved in the transactions and how much value has been transacted. or anything else that you want to ask the network.</p>
<p> Bitcoin is opensource and there are plenty of APIs out there that you can use to query the blockchain. Even better if you run your own full node and build your analytics platform around it!</p>
<p>blockchain.com provides a suite of APIs that you can tap into. <a>https://www.blockchain.com/api</a></p>

In [1]:
# install networkx library for transaction network graph visualisation
#!pip install networkx

In [2]:
import requests
import json
import pandas as pd
import datetime

In [3]:
import networkx as nx

ModuleNotFoundError: No module named 'networkx'

# Make a get request to the https://blockchain.info/latestblock

In [ ]:
latest_block= "https://blockchain.info/latestblock"
x = requests.get(latest_block)
print(x.status_code)

200

In [ ]:
x.json()

{'hash': '00000000000000000000faf43a4490b5da4f051561ba547a1d4ecd343f8e0630',
 'time': 1760948953,
 'block_index': 919924,
 'height': 919924,
 'txIndexes': [871279596382241,
  2232880464926398,
  3446773793856230,
  840147452359027,
  1003784970491209,
  198020349290085,
  409777316705071,
  954832203978950,
  1402554443603770,
  1641974929564681,
  2837302983866584,
  3109172949696708,
  3451558529559701,
  3575862431497860,
  3705026508622829,
  4199027958607409,
  4643344642766868,
  5628940374262528,
  7338168594882610,
  8400225103902672,
  8849013748646500,
  8951355715146233,
  6979933798847252,
  8995534630989380,
  7527985784571996,
  1854929400748660,
  5585068569562552,
  4807035378697970,
  8298714430121671,
  9004915414460977,
  573618338271904,
  5348773764202629,
  1912696660105239,
  556916672429499,
  1352462018173194,
  1809922403653831,
  2514066432895623,
  6715198199204032,
  8304522159461927,
  8887592950373579,
  5407995641499217,
  7678296283181499,
  958578639547964,
  1020315077029811,
  2071751369704739,
  7399367776916777,
  6483444769741156,
  7231775150222427,
  2824997223328966,
  938487167154797,
  3811813389147492,
  4343440545084392,
  4729894240013924,
  4751429588948701,
  6269367338642120,
  6822003392661031,
  7961769359474934,
  2550024315267371,
  2617903143519305,
  2715712518006692,
  4907860529314019,
  2931773540693677,
  5684563212717078,
  4513607483436186,
  8518876120241472,
  2808658398389145,
  8241926474513460,
  7944241545412533,
  5342294396288586,
  8595778997256212,
  695910705845756,
  718445247520385,
  1265293873192965,
  2812064469296838,
  3041831782466755,
  6376129938157701,
  7454122540555472,
  8540887456208994,
  648662367559120,
  5507361050189195,
  5984710896541252,
  6326885182866490,
  1001313856055095,
  5937583641091404,
  71880258871347,
  3856630671723132,
  1724737856411087,
  4381846758684576,
  4545471888703521,
  4971728390907629,
  8586940446379982,
  442805232736369,
  2768933111117443,
  6915471385911093,
  5647395159003924,
  2393434937795748,
  8482339600934372,
  2652941915812423,
  5488525525788882,
  8890140109266314,
  8979891756422383,
  3728307907680512,
  6585028219765393,
  5226816605183163,
  6390331134301381,
  7286083365574090,
  5288448660357645,
  5418029608327509,
  5991728745272924,
  503847908670581,
  7713658631685508,
  8362934283753879,
  2696663337794094,
  1935822389331987,
  1151317728841329,
  4120919670775826,
  5508385989071221,
  3913737555136833,
  1277302977640669,
  7119878336354910,
  2492561227102389,
  6490641840374187,
  2183674240170853,
  4479386581960399,
  7457130348560156,
  8668300666075257,
  5004353084112210,
  7806107458577810,
  7817467699261874,
  5664959620238377,
  5755017490611386,
  1646106798516763,
  2213562215953764,
  4163884151180025,
  7518219135685511,
  4393734785613529,
  3957962170998736,
  8874763392090168,
  3287919280946742,
  1099633466378857,
  4142807873627538,
  7647519007562292,
  7224567758581215,
  8558069752088939,
  3442455351521466,
  1457221628095883,
  5984707898517398,
  8320701763955927,
  6440532902111057,
  2702797142994064,
  7842241626105013,
  5743302703165802,
  1474324946106542,
  896658309667187,
  8929817871284983,
  5043305592121895,
  7160577602370658,
  6706564038622044,
  3124816108475877,
  203366420955612,
  438227387563801,
  6870230517589709,
  2729522943491291,
  6477977799595601,
  7089263254406150,
  489615384503251,
  1171870889223499,
  1654830481379213,
  1923788439843827,
  2664944743332409,
  2865346735712825,
  3376439070217341,
  3444753065987903,
  3633822626132879,
  4172440657557628,
  4302942443310292,
  4538741009784367,
  5150530268736716,
  7484072976027284,
  7946258370733197,
  8447207986181239,
  8465643515154283,
  8641103294780769,
  4055019904473976,
  8493962797807348,
  5970498748533241,
  6879070382352360,
  4606985627711292,
  7987179896461654,
  4310230755941387,
  7275503172672086,
  5586710204633334,
  5583677188261176,
  6496241839734595,
  2831955569278286,
  7103735726173949,
  5149863172018274,
  6271157377736003,
  838488116493248,
  4007983100253198,
  5282912563196889,
  4912396521050548,
  6541146984364028,
  5465907122130545,
  2452357952552786,
  7486205013540349,
  2284510469189615,
  5422142120539538,
  2852399339639165,
  8440238628869002,
  3242093018504559,
  389367265252281,
  3529518647073082,
  8468448521649162,
  5831909533273812,
  7606121632994609,
  6570010111588404,
  8715269282359495,
  2012664864350571,
  802132462280770,
  1011636988829734,
  1136352799808757,
  2440549507448861,
  2873113147532498,
  3688833286592641,
  3824721742890685,
  4806679759156375,
  5949277951121885,
  6137282610377030,
  7056165108058226,
  7161784427843772,
  8374979525673032,
  1845218816171216,
  6169845836103,
  7323493678831681,
  445778153172495,
  7856154156471057,
  8125349487139193,
  7357422439836623,
  6848551615758177,
  7195042074266701,
  2447147898455310,
  17160225592881,
  3460088310188203,
  1651510067184176,
  2768562780861347,
  5061699928310950,
  1200722428401955,
  4729078190706624,
  6193147051612731,
  5800261101482135,
  3466600664231915,
  1311240574617664,
  6152668897747891,
  6809969874029907,
  6565214240726464,
  2011011252313822,
  2638073159910384,
  6342333576668103,
  4141441335101759,
  4304273397354975,
  5974028660327839,
  2842913347990605,
  2557749931370466,
  8617966098367102,
  1123279385179049,
  8635703375174363,
  8778008803364186,
  5784084759663885,
  4213836483955187,
  6342077295299763,
  5594411930954651,
  5588976612007669,
  1152943447111118,
  948518421997429,
  1468950766937046,
  5030021985920720,
  7720642871932768,
  8077085361748569,
  8450521076830582,
  247507268551906,
  1420491350856236,
  92977530067189,
  3429105144871920,
  3975412075308212,
  6343580223665268,
  279504640808380,
  7569499735969769,
  2109311797826873,
  4845120401145057,
  5665868921058294,
  2241339924098225,
  2615829296434364,
  6002792033293180,
  975862829452768,
  5967963602697629,
  6905673357025048,
  2969083886791699,
  5602190658700804,
  6543960431926598,
  7512070378136918,
  1325355218547391,
  4728487996071973,
  3933800134740956,
  4443676947633,
  2018119380311929,
  3370862483730671,
  8699416720668644,
  794561131513714,
  129337504533759,
  152247937354049,
  169404059420900,
  413933827717122,
  429347413360902,
  477009958780256,
  498793104605656,
  656876411074852,
  834807804456412,
  982318320652963,
  997829056424034,
  1179994787127667,
  1318457919199891,
  1375064216508879,
  1441599163139737,
  1543436116870278,
  1711632130024447,
  1777534132044344,
  5919143279920480,
  1834126732069327,
  1979084842669233,
  2022158042692328,
  2050565831343706,
  2513497179965203,
  2785168241519943,
  2814419875487221,
  2924504035008261,
  3096682254704292,
  3758328153381243,
  4032739124447208,
  4179563430688386,
  4835806785345726,
  4842072745557404,
  5021821712738928,
  5193085747788153,
  5583691015225301,
  5636774814160259,
  5730006182937385,
  5730761825618009,
  6082880032119947,
  6136334292176965,
  6224177202426892,
  6279219903870263,
  6938648633641193,
  6994447561165830,
  7005121967957563,
  7090000275618266,
  7104698938837542,
  7699999696808726,
  7804298326179514,
  7962618814951808,
  8242734737239113,
  8263032791775467,
  8313333785256894,
  8353149231129090,
  8540997076662317,
  8682409031632222,
  8999773459480754,
  3291666150905022,
  5938050566341843,
  6518305458638192,
  8005256926876769,
  1287059872228293,
  2674495700005189,
  8356685219834041,
  4400994498045276,
  5490117822736039,
  6048566833728986,
  4371185043943137,
  8810209304849805,
  6482309179241398,
  2043379380221605,
  3974586576800167,
  4232062363399251,
  8975275720374022,
  4680121496931968,
  6204984090836651,
  6291215714933842,
  7349222475895389,
  7800091328116804,
  1684443650552619,
  3466120486781659,
  4292277155006537,
  1704039688202450,
  866421646549590,
  5407002149311568,
  6668727028012683,
  2049447125774526,
  2782350856049222,
  5861876284712002,
  7238716207165521,
  5946256470508544,
  558225969498215,
  1410787379973986,
  5113070479003790,
  5974904657892890,
  3159621159665169,
  1832489539739244,
  94194674146179,
  5933611428310244,
  6234103594911402,
  1675040467094208,
  1086890197556814,
  7091953450547141,
  4368649842316341,
  1744630859356511,
  773113744743459,
  777335633741983,
  1178087488402532,
  8417320794969449,
  1082653633377613,
  2113512176953756,
  2529370396926228,
  816931612485750,
  1165789822588892,
  1188856399011592,
  1323024038036730,
  1923322514240582,
  2245410839361830,
  2744763329061167,
  3142501476558638,
  3330567960874051,
  3932614870763110,
  4165629001813648,
  4436523735768684,
  4667149223263476,
  5172718816048313,
  5349924956050577,
  6100229165330158,
  6630788212628889,
  6749401474066388,
  7290287957122935,
  7357581338778519,
  8415133961555412,
  8985334054726442,
  334145278724875,
  3759774100388963,
  8265821481108292,
  6993317220046033,
  67138957328398,
  546110361150927,
  605729782725459,
  616279286220178,
  708949499285835,
  714813424257155,
  859355124343067,
  918852953958813,
  1260624068623333,
  1658534916759844,
  1820723879052822,
  2326079993996101,
  2395185338985521,
  2566677047973218,
  2761665169977313,
  2975949025658034,
  2986309652113853,
  3175400934088969,
  3287102826357994,
  3445789742562675,
  3814573647786315,
  3847105049845837,
  4096347679364163,
  4210992475421877,
  4447137580196769,
  4641387856287062,
  4806241781929081,
  5062722868306636,
  5392240640443086,
  5600002947740353,
  5821595472387840,
  5881714589780683,
  6025566123210751,
  6239822712966135,
  6398055171747223,
  6558053442583399,
  6780068069902625,
  7306647385897192,
  7771347284296664,
  7883963260566161,
  7955887281615205,
  7961703385192723,
  8183211900480677,
  8263313081207960,
  8487169733924665,
  8709257520493207,
  8978126178606623,
  2657705920575569,
  6052124037461413,
  2724123952054115,
  5831873015656334,
  7880299285072814,
  5547563325417652,
  1829195739122085,
  4203437509659884,
  2931819107840203,
  2170568803259715,
  7441613864971023,
  1378197196723955,
  5843521940044849,
  1215463154619390,
  2794312166563421,
  192220219582508,
  1700413664113546,
  3987479081321833,
  5934099088223716,
  6273791514891177,
  7272246673831394,
  7625942480261284,
  8515155799503619,
  7471601952615961,
  1480748574771451,
  1549435794498082,
  7468088338232598,
  7861041765011948,
  2615225636508782,
  8759612124872618,
  932723906073095,
  5188927952700698,
  8093475900887840,
  8492697575205806,
  636843830632169,
  643607091005514,
  846211134951993,
  2314115247779191,
  2327234368505475,
  2334845989670944,
  3790701204610293,
  4959214485772350,
  5500029645654061,
  5632794389720486,
  6502501475618864,
  6816996882350569,
  7291982791995908,
  8307958553585630,
  352769127357701,
  1342865925805361,
  8417668207637504,
  3553811954471388,
  2240858160495,
  1865555593311141,
  2374937941908809,
  2820294356337036,
  3952205746868786,
  5169147124940975,
  5996668705185698,
  6184019183524713,
  7041977234174802,
  7300953356804366,
  8069375097391987,
  8732279794320949,
  5943266231038908,
  4930999557896526,
  4456242067608326,
  6764829845843996,
  6923879136544987,
  7128528761148881,
  1435072050997317,
  8481200476035528,
  5881624212342982,
  8995969115702410,
  8031370682712847,
  2410368608226752,
  8487004588672750,
  1700567111353656,
  3367114035515753,
  4702936639555560,
  5769137876618054,
  6183187516371524,
  8283282278415363,
  3793507955530468,
  6371475103576914,
  950849831459840,
  2382713171479444,
  3714260752355387,
  3395545627506784,
  7100727292596974,
  7135141058317216,
  8510541340440313,
  5122650137399956,
  8169441961947926,
  5151335906328195,
  6097275038923302,
  5230825836491747,
  4280985426712068,
  2213909185533358,
  1960031933284923,
  2465337819350704,
  4556541307520265,
  3324881138979681,
  6392297139098167,
  3922357897021430,
  3059028454336238,
  1547022383203196,
  8395388946031374,
  5048584717173031,
  1087830157903390,
  1922457298393600,
  1604913568554094,
  638401157007630,
  4035300476261556,
  4531482892767070,
  5736489726600334,
  2707499933492855,
  1021704265645570,
  1703868096784263,
  3282507707091090,
  8456354674139325,
  5077028020461742,
  3901036873338146,
  5047770567353893,
  5850016755594581,
  32637588219666,
  1612994874969054,
  1878986815134724,
  893063074806913,
  597607647954119,
  8816552092349615,
  7834866623713442,
  7649570087168244,
  6991618370546477,
  3906896203256948,
  5658507304755996,
  5398369377025968,
  2755683130481213,
  2239858815240438,
  6564497036017893,
  1450632570644631,
  1598851080548583,
  4237470080259877,
  9000965002071155,
  4922419153530033,
  4133739692382535,
  110310259303871,
  2737077167809839,
  3172645936167374,
  1181909670905271,
  7140239739355922,
  1708359784144477,
  3137869907351292,
  165954176330399,
  8315832051056975,
  8737685992449198,
  3568870088539833,
  523631616265892,
  2966875625834751,
  3948486064954342,
  1286815044499904,
  3918599331067362,
  7919537606331633,
  1422428529939579,
  8100600758163805,
  1297985905588447,
  459247112251810,
  4497846394327170,
  8773245967461499,
  4721968262314010,
  5545418917577418,
  8328485885977549,
  8718520196928169,
  7545471878758050,
  2790265033592585,
  7433762005226952,
  3181053683243852,
  4612734298416687,
  5588979458579791,
  5812831044496666,
  7743577747419806,
  1279548477634424,
  2514967875456264,
  3314529587621042,
  5475022064074271,
  5924723399396307,
  4879762631292936,
  188346331236862,
  4016818756317196,
  2102570433586219,
  1053553870164547,
  8741149125646124,
  6443850110911184,
  8418127093937660,
  7229872689280700,
  1129884254901653,
  166288967701123,
  1552848746834790,
  1026147500678,
  38475256015770,
  46833936842179,
  79977176687252,
  104082492598502,
  152226433906265,
  159050218811962,
  179956739037372,
  189345184448362,
  266650918235174,
  443920231433318,
  480497755114827,
  558745544318307,
  578090814047698,
  590212209986713,
  648442200415563,
  656666679249739,
  657524379190678,
  939642660610705,
  963743749945085,
  1025710063682549,
  1055943801631110,
  1102978588406057,
  1132965729044741,
  1261413319521848,
  1341537803010424,
  1401960008694148,
  1408419759684574,
  1454343534812985,
  1489272685475865,
  1499750235947602,
  1594016613577349,
  1679729119080262,
  1713746884378922,
  1722799618423193,
  1768749666809129,
  1782478118067026,
  1878659671943190,
  1912951971236475,
  1970042432581589,
  2183728357984904,
  2237960084765047,
  2243641866345272,
  2294130631656053,
  2474196935791001,
  2489700174148694,
  2561188116004907,
  2570385008510489,
  2601412869925929,
  2624795805514928,
  2787348322533403,
  2788540172420408,
  2868143338259877,
  2897492772349889,
  2947676083036082,
  3003606055480921,
  3031563038069248,
  3035359476128676,
  3101210465530677,
  4944095245141828,
  3127113386028607,
  3255852113594528,
  3259998011547133,
  3278725506759073,
  3428893941562066,
  3459164522543593,
  3524366949438875,
  3536812736978386,
  3672552689816313,
  3674914517935295,
  3727077585549579,
  3730536780184887,
  3731945452516005,
  3758134627133696,
  3834932598723881,
  3840515477250285,
  3886260260660544,
  3908277533452121,
  3922005402536595,
  3942134598515722,
  4033532490262091,
  4120739985706617,
  4165562413696946,
  4354337099204116,
  4461746707966901,
  4462039169689175,
  4470831728479360,
  4475256197844516,
  4515973888528366,
  4599996694757029,
  4602408266794546,
  4625724059440391,
  4696080340863995,
  4699880242367982,
  4733835441243801,
  4852718675563439,
  4865107085136652,
  4966473232289313,
  5045657692036418,
  5184818302430248,
  5185639619703468,
  5205252142643578,
  5245647662089432,
  5247930602730421,
  5345246310572156,
  5389524643421536,
  5415345094103732,
  5548950861528519,
  5591398843376323,
  5685977629031898,
  5714822958001765,
  5812854627416593,
  6066001670635533,
  6082788441381628,
  6094321790443395,
  6167254130036188,
  6174465721148878,
  6195156182730269,
  6232447051897986,
  6304367294230752,
  6319443095507583,
  6334215203330559,
  6367644207418365,
  6385208033252240,
  6391511721553076,
  6415775537619161,
  6463536195081182,
  6489391455245035,
  6635175081560809,
  6702567080762649,
  6718336843352649,
  6740149490680958,
  6756570629624534,
  6857244889831893,
  6938796632460471,
  6965459516059587,
  6998053422436067,
  7023271694987636,
  7038313503496686,
  7112900322552650,
  7155650203495160,
  7158720007093765,
  7178567869789310,
  7215820367431693,
  7290039317905862,
  7343365768334049,
  7353351317958672,
  7404463670848117,
  7407120221574323,
  7435984248203922,
  7542467886490951,
  7547808633213686,
  7548841109210371,
  7643743511801817,
  7689896168428081,
  7835977274594919,
  7969370820655342,
  8035449625159155,
  7987322736351229,
  8044884387510171,
  8059737583627199,
  8076257084208329,
  8237140259518351,
  8349433657222370,
  8422221688879544,
  8438329150699847,
  8475320248891361,
  8482427749747491,
  8537529100056948,
  8541907900470053,
  8605420278649114,
  8700501188430714,
  8721567463111196,
  8796052071159650,
  8871647828335442,
  8910485423528284,
  8933229023317170,
  8938225155389397,
  8994963894133545,
  1003962818176933,
  3024617975552105,
  4004728338258003,
  5517305469917909,
  2609394943920780,
  2626164585005051,
  8555752560741399,
  1431570426981442,
  2191517098409398,
  6283829811035483,
  8621978981114833,
  1123261700055440,
  7184347300751649,
  7561379581104035,
  3182579355769981,
  1125118330852130,
  3299779819981145,
  8061418573779328,
  2979656797711383,
  7899315587467573,
  7930453771876019,
  5125424247617880,
  4838360834997173,
  6944920326175991,
  7189814601207087,
  393764682423283,
  1455998174030286,
  7328087096793437,
  2366883341271300,
  1628175980730005,
  5169258311051946,
  5930770512928984,
  1253957693859844,
  886422855515370,
  3224580544399164,
  989653965701176,
  6413156772751564,
  4605239864974709,
  4574220290850966,
  4621169465952350,
  7148893751550715,
  144273654036356,
  360477576391311,
  2294005705178975,
  3346641229341927,
  8215795454839596,
  8663433996989423,
  1045088450033056,
  1342116199963047,
  1404828469026159,
  3577762231733820,
  5860481627922701,
  8903454803603545,
  5772704488160381,
  239808674708508,
  5438672807861278,
  3943780007035967,
  6803132822832534,
  4470437132509580,
  1978188345267277,
  6693106210299602,
  1967538643156853,
  8857290895990118,
  402385504214263,
  1111557147859250,
  1016853719486394,
  3357324630592540,
  4960062449299186,
  7545318202225526,
  4976888559481946,
  8263765203535233,
  7663892827015251,
  2925319670834739,
  3600778224794578,
  7037104022565970,
  6642434252913764,
  3044155586957269,
  2549443245515232,
  3281388899634163,
  7362247997047222,
  2160495150338459,
  288521003516211,
  1733986169987987,
  7303969551908237,
  7530863248970353,
  2326539173520475,
  5062250702694018,
  6151737560085559,
  4809046088592768,
  6162184374390698,
  2440290133526799,
  8205197083411149,
  3868453554524708,
  284695916983782,
  619483386105669,
  744323228395391,
  950068516090943,
  983301179987405,
  1034053627480027,
  2945399584123513,
  3876546111676369,
  4455349469019080,
  4817583859203650,
  5269675940814583,
  8105261650116618,
  8239703010935375,
  8623416791964469,
  1705263383187177,
  3813099719201452,
  3524700404945158,
  3984885155598,
  2353581985659532,
  2395103379601791,
  7514349816298912,
  7599242652882267,
  8763006143329291,
  2027322744775811,
  3249727020366717,
  6001644090479274,
  6786515703803631,
  7360964950971648,
  7488446836882026,
  3704968554466015,
  8388080245873172,
  2348832431863474,
  149373485592660,

# When was this block mined? Format the date in human readable format (use datetime functions).

In [ ]:
time_val = (x.json()['time'])
from datetime import datetime as datetime
readable_date = datetime.utcfromtimestamp(time_val)
# = datetime.utcfromtimestamp(time_val).strftime('%Y-%m-%d %H:%M:%S')

/tmp/ipython-input-1834500950.py:3: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
  readable_date = datetime.utcfromtimestamp(time_val)

In [ ]:
print("the latest block was mined on", readable_date)

the latest block was mined on 2025-10-20 08:29:13

# What is the height of the longest chain aka current blockchain height?

In [ ]:
print("the height of the longest chain is {} blocks.".format(x.json()['height']))

the height of the longest chain is 919924 blocks.

Can you work out the height of the next block?

# What is the current block hash?

In [ ]:
print("The hash of the current block is {}".format(x.json()['hash']))

The hash of the current block is 00000000000000000000faf43a4490b5da4f051561ba547a1d4ecd343f8e0630

# Create a dataframe with all transaction indexes.

We will use this transaction indexes to get tranasction information and query for balances held by each bitcoin address invloved in the transactions...

In [ ]:
df_tx = pd.DataFrame(x.json()['txIndexes'])

In [ ]:
df_tx

                     0
0      871279596382241
1     2232880464926398
2     3446773793856230
3      840147452359027
4     1003784970491209
...                ...
1878  8812346372493356
1879  8854941113291935
1880  8885087823321561
1881  8912521010291255
1882  8979005561725265

[1883 rows x 1 columns]

# How many total Transactions does this block contain?

In [ ]:
no_tx = df_tx.shape[0]

In [ ]:
 no_tx

1883

# Take any transaction index from the dataframe you have just createda and get the transaction information. https://blockchain.info/rawtx/$tx_index

In [ ]:
tx_info_url= "https://blockchain.info/rawtx/"

In [ ]:
tx_index = str(df_tx.loc[no_tx-1].values[0])

In [ ]:
tx_info_url_2 = tx_info_url+tx_index

tx_data = requests.get(tx_info_url_2)
print(tx_data.status_code)

print (tx_data.json())

200
{'hash': '3737dc7a240adca4318fb5ae4c04f360b1d4f4f0176ffdd2908b0a8b27dd32ff', 'ver': 2, 'vin_sz': 1, 'vout_sz': 2, 'size': 222, 'weight': 561, 'fee': 141, 'relayed_by': '0.0.0.0', 'lock_time': 919923, 'tx_index': 8979005561725265, 'double_spend': False, 'time': 1760948460, 'block_index': 919924, 'block_height': 919924, 'inputs': [{'sequence': 4294967293, 'witness': '024730440220672b6380a980d2a5b2692834c13a3e92eafb121da8ea774764dfa27aa725b5d20220133f1cb00f173652c9377d7b24cd5f8537d0bd7bfe080e15799c4c8f567a443f0121025fcb4cd7d52bc2ec96db7cabbf4b2e8fe024956737fe32400f7a52fb52ea5d50', 'script': '', 'index': 0, 'prev_out': {'type': 0, 'spent': True, 'value': 9721679, 'spending_outpoints': [{'tx_index': 8979005561725265, 'n': 0}], 'n': 1, 'tx_index': 3156556647920374, 'script': '0014901e5054d313bd9671754941199363278c706a0b', 'addr': 'bc1qjq09q4xnzw7evut4f9q3nymry7x8q6styc3fts'}}], 'out': [{'type': 0, 'spent': False, 'value': 1381767, 'spending_outpoints': [], 'n': 0, 'tx_index': 8979005561725265, 'script': '00146c9c07865284ad8e5d872458ae0e157d075f5250', 'addr': 'bc1qdjwq0pjjsjkcuhv8y3v2urs405r475js84aud8'}, {'type': 0, 'spent': False, 'value': 8339771, 'spending_outpoints': [], 'n': 1, 'tx_index': 8979005561725265, 'script': '00145c9c3ea4cc002b8756eb61466e1a49f363620a88', 'addr': 'bc1qtjwrafxvqq4cw4htv9rxuxjf7d3kyz5g92wc5l'}]}

How many inputs and outputs this transaction contains?

In [ ]:
no_inputs = len(tx_data.json()['inputs'])
no_outputs = len(tx_data.json()['out'])

In [ ]:
print (no_inputs, no_outputs)

1 2

# How many bitcoins have they sent/ recieved and what the current balances are?

In [ ]:
inputs = tx_data.json()['inputs']
outputs = tx_data.json()['out']

In [ ]:
for i in inputs:
    btc_val = (i['prev_out']['value']/10e8)
    print (btc_val)

print ()

for i in outputs:
    btc_val = (i['value']/10e8)
    print (btc_val)

0.009721679

0.001381767
0.008339771

In [ ]:
wallet_lookup_url="https://blockchain.info/balance?active="

for i in inputs:

    addr = (i['prev_out']['addr'])
    w = requests.get(wallet_lookup_url+addr)
    print (w.json())

print ()

for i in outputs:
    addr = (i['addr'])
    w = requests.get(wallet_lookup_url+addr)
    print (w.json())

{'bc1qjq09q4xnzw7evut4f9q3nymry7x8q6styc3fts': {'final_balance': 0, 'n_tx': 2, 'total_received': 9721679}}

{'bc1qdjwq0pjjsjkcuhv8y3v2urs405r475js84aud8': {'final_balance': 1381767, 'n_tx': 1, 'total_received': 1381767}}
{'bc1qtjwrafxvqq4cw4htv9rxuxjf7d3kyz5g92wc5l': {'final_balance': 8339771, 'n_tx': 1, 'total_received': 8339771}}

# Create a datframe with senders and receivers of some of the transactions

In [ ]:
# Extract value and addr
df_in = pd.DataFrame([{'value': item['prev_out']['value'], 'addr': item['prev_out']['addr']} for item in inputs])
df_out= pd.DataFrame(outputs)

# addr, direction, value

In [ ]:
df_in

     value                                        addr
0  9721679  bc1qjq09q4xnzw7evut4f9q3nymry7x8q6styc3fts

# Let us visulaise the transaction(s)

In [ ]:
G = nx.Graph()

In [ ]:
G = nx.from_pandas_edgelist(df, 'sender', 'receiver_addr')

NameError: name 'df' is not defined

In [ ]:
from matplotlib.pyplot import figure
figure(figsize=(10, 8))
nx.draw_shell(G, with_labels=True, node_color="red")

# Which addresses are occuring frequently?

In [ ]:
leaderboard = {}
for x in G.nodes:
 leaderboard[x] = len(G[x])
s = pd.Series(leaderboard, name='observed')
df2 = s.to_frame().sort_values('observed', ascending=False)

In [ ]:
df2

# Collect all inputs and outputs of the block and create a detailed network map.

In [ ]:
final_df=pd.DataFrame()
for index, row in df_tx.loc[1:10].iterrows():
    df= getBlockchainData(row.Tx_indexes)
    final_df= final_df.append(df)

In [ ]:
final_df

In [ ]:
df= final_df
from matplotlib.pyplot import figure

G = nx.Graph()
G = nx.from_pandas_edgelist(df, 'sender', 'receiver_addr')
figure(figsize=(10, 8))
nx.draw_shell(G, with_labels=True)

In [ ]:
def getBlockchainData(tx):
    tx_info_url= "https://blockchain.info/rawtx/"
    tx_info=  requests.get(tx_info_url+str(tx))
    df_out= pd.DataFrame(tx_info.json()['out'])
    df_out= df_out[['value', 'addr']]
    df_out.columns= ['output_value', 'receiver_addr']
    df_ins= pd.DataFrame(tx_info.json()['inputs'][0]['prev_out'])
    df_ins= df_ins[['addr']]
    df_ins.columns= ['sender_addr']
    df= df_out
    df['sender']= df.apply(lambda x: df_ins.sender_addr, axis= 1 )
    return df